# 예외 처리

> try 블록에서 NullPointerException이 발생하면 catch 블록을 실행해서 예외를 처리하도록 하고. 예외 발생 여부와 상관없이 finally 블록을 실행하여 마무리 작업
> 
- 예외 처리를 여러개 만들어 두었다 하더라도 예외처리는 하나만 실행
- 발생된 예외는 catch문의 순서에 맞추어 해당되는 예외클래스를 탐색 후 일치하는 클래스가 있으면, 해당 catch 블록을 수행
- 일치하는 클래스가 없다면 현재 메서드를 호출한 메서드로 예외 객체를 던진다.
- catch에 사용되는 예외클래스의 순서는 상위 클래스를 제일 밑에 배치하도록 한다.

```java
package sec01;

public class ExceptionHandlingExample1 {

	public static void main(String[] args) {
		System.out.println("［프로그램 시작］\n");
		printLength ("ThisIsJava");
		printLength(null); 
		System.out.println("|프로그램 종료|");
	}
	
	public static void printLength(String data) {
		try {
			int res = data.length();
			System.out.println("문자 수 : " + res);
		}
		catch(NullPointerException e) {
			System.out.println(e.getMessage()); // 3개 다 가능하다.
			System.out.println(e.toString());
			e.printStackTrace();
		}
		finally {
			System.out.println("[마무리 실행]");
		}
	}

}

[프로그램 시작］

문자 수: 10
[마무리 실행］

Cannot invoke "String.lengthO” beca니se "data" is nu11 // e.getMessage()
java.lang.NullPointerException: Cannot invoke "String.length()" because "data" is null // e.toString()
java.lang.NullPointerException: Cannot invoke "String.length()" because "data" is null
	at sec01.ExceptionHandlingExample1.printLength(ExceptionHandlingExample1.java:14)
	at sec01.ExceptionHandlingExample1.main(ExceptionHandlingExample1.java:8) // e.printStackTrace()
［마무리 실행］

［프로그램 종료］
```

```java
package sec01;

public class ExceptionHandlingExample4 {

	public static void main(String[] args) {
		String[] array = {"100", "1oo", null, "200"};
				
		for(int i=0; i<=array.length; i++){
			try {
			int value = Integer.parseInt(array[i]);
			System.out.println("array[" + i + "]: " + value);
			}
			catch (ArrayIndexOutOfBoundsException e) {
				System.out.println("배열 인덱스가 초과됨 : " + e.getMessage());
			}
			catch (NullPointerException | NumberFormatException e) {
				System.out.println("데이터에 문제가 있음 : " + e.getMessage());
			}
			catch (Exception e) {
				System.out.println("실행에 문제가 있습니다.");
			}
		}
			
	}
}

array[0]: 100
데이터에 문제가 있음 : For input string: "1oo"
데이터에 문제가 있음 : Cannot parse null string
array[3]: 200
배열 인덱스가 초과됨 : Index 4 out of bounds for length 4
```

---

## 예외 객체의 주요 메서드

- String getMessage() : 예외가 발생한 이유만 리턴
- String toString() : 이유 + 예외의 종류도 리턴한다.
- void printStackTrace() : 이유 + 종류 + 예외가 어디서 발생했는지 추적한 내용까지도 출력해준다.

---

## 예외 종류

- NumberFormatException : 숫자형으로 표현할 수 없을 경우 발생
- ArrayIndexOutOfBoundsException : 배열의 인덱스 범위를 벗어나는 경우
- NullPointerException : 참조변수가 null인 상태에서 필드나 메서드를 호출한 경우 발생
- ClassNotFoundException : 클래스를 찾지 못한 경우 발생

---

# 리소스 자동 닫기

```java
package sec01;

public class MyResource implements AutoCloseable {
	private String name;
	
	public MyResource(String name) {
		this.name = name;
		System.out.println("[MyResource(" + name + ") 열기]");
	}
	
	public String read1() {
		System.out.println("[MyResource(" + name + ") 읽기]");
		return "100";
	}
	
	public String read2() {
		System.out.println("[MyResource(" + name + ") 읽기]");
		return "abc";
	}

	@Override
	public void close() throws Exception {
		System.out.println("[MyResource(" + name + ") 닫기]");
	}

}

//

package sec01;

public class TryWithResourceExample {

	public static void main(String[] args) {
		try (MyResource res = new MyResource("A")) {
			String data = res.read1();
			int value = Integer.parseInt(data);
		}
		catch (Exception e) {
			System.out.println("예외 처리 : " + e.getMessage());
		}
		
		System.out.println();
		
		try (MyResource res = new MyResource("A")) {
			String data = res.read1();
			int value = Integer.parseInt(data);
		}
		catch (Exception e) {
			System.out.println("예외 처리 : " + e.getMessage());
		}
		
		System.out.println();
		
		MyResource res1 = new MyResource("A");
		MyResource res2 = new MyResource("B");
		try (res1; res2) {
			String data1 = res1.read1();
			String data2 = res2.read1();
		}
		catch (Exception e) {
			System.out.println("예외 처리 : " + e.getMessage());
		}
	}

}
```

---

# 확인 문제

```java
7. 로그인 기능을 Member 클래스의 login() 메소드에서 구현하려고 합니다. 존재하지 않는 ID를 입력했을 경우 
NotExistIDException을 발생시키고, 잘못된 패스워드를 입력했을 경우 WrongPasswordException을 발생시키려고 합니다. 
LoginExample의 실행 결과를 보고 빈칸을 채워보세요.

package Example;

public class NotExistIDException extends Exception {
	public NotExistIDException() {}
	public NotExistIDException(String message) {
		super(message);
	}

}

//

package Example;

public class WrongPasswordException extends Exception {
	public WrongPasswordException() {}
	public WrongPasswordException(String message) {
		super(message);
	}

}

//

package Example;

public class LoginExample {
	public static void main(String[] args)  {
		try {
			login("white", "12345");
		}
		catch(Exception e) {
			System.out.println(e.getMessage());
		}
		
		try {
			login("blue", "54321");
		}
		catch (Exception e) {
			System.out.println(e.getMessage());
		}
	}
		
	public static void login(String id, String password) throws NotExistIDException, WrongPasswordException {
		if(!id.equals("blue")) {
			throw new NotExistIDException("아이디가 존재하지 않습니다.");
		}
		
		if(!password.equals("12345")) {
			throw new WrongPasswordException("패스워드가 틀립니다.");
		}
		
	}
	
}
```

---

# 예외처리 메서드 오버라이딩

### **메서드 오버라이딩(Method Overriding)시에 throws문 규칙에 대해**

> 메서드를 오버라이딩 할때에는 상위 클래스나 인터페이스의 메서드 선언부에 따라 그것을 오버라이딩 할때 제약을 받게되는데, 그 중 하나는 예외를 떠넘기는 throws에 대한 규칙입니다.
> 
> 
> 규칙에 대해 앞서 말하자면 메서드 오버라이딩시에 하위 클래스는 예외를 throws 하지 않거나, 자신이 상속받은 상위 클래스의 메서드보다 같거나 하위의 예외만을 throws할 수 있습니다.
> 

1. 상위클래스의 메서드에서 throws를 선언했더라도 하위클래스는 throws 처리를 하지 않을 수 있다.

2. 하위클래스는 상위클래스의 메서드에서 throws 하는 예외와 같은 예외를 throws 할 수 있다.

3. 하위클래스는 상위클래스의 메서드에서 throws 하는 예외의 하위 예외만 throws 할 수 있다.

4. 하위클래스는 Runtime 예외(Unchecked) 예외를 상위클래스의 메서드와 관계없이 throws 할 수 있다.

---

# 사용자 정의 예외

> 사용자 정의 예외는 컴파일러가 체크하는 일반 예외로 선언할 수도 있고, 컴파일러가 체크하지 않는 실행 예외로 선언할 수도 있다. 통상적으로 일반 예외는 Exception의 자식 클래스로 선언하고, 실행 예외는 RuntimeException의 자식 클래스로 선언한다
> 

> 사용자 정의 예외 클래스에는 기본 생성자와 예외 메시지를 입력받는 생성자를 선언해준다. 예외 메시지는 부모 생성자 매개값으로 넘겨주는데. 그 이유는 예외 객체의 공통 메소드인 getMessage()의 리턴값으로 사용하기 위해서이다.
> 

```java
package sec01;

public class Account {
	private long balance;
	
	public Account() {
		
	}
	
	public long getBalance() {
		return balance;
	}
	
	public void deposit(int money) {
		balance += money;
	}
	
	public void withdraw(int money) throws InsufficientException {
		if(balance < money) {
			throw new InsufficientException("잔고 부족 : " + (money - balance) + " 모자람");
		}
		balance -= money;
	}

}

//

package sec01;

public class AccountExample {

	public static void main(String[] args) {
		Account account = new Account();
		
		account.deposit(10000);
		System.out.println("예금액 : " + account.getBalance());
		
		try {
			account.withdraw(30000);
		}
		catch(InsufficientException e) {
			String message = e.getMessage();
			System.out.println(message);
		}
	}

}
```
